name: example
description: an example
version: 0.0.1+1

environment:
  flutter: ">=1.2.0 <2.0.0"
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_persistent_queue:
    path: ../

flutter:
  uses-material-design: true
