name: flutter_persistent_queue
description: >
  Simple file-based non-volatile persistent queue implementation for flutter.
  Ideal for in-device sequential buffers that must persist between app runs.
version: 1.0.2
author: Romulo Carvalho <oakromulo@gmail.com>
homepage: https://github.com/oakromulo/flutter_persistent_queue
repository: https://github.com/oakromulo/flutter_persistent_queue.git
issue_tracker: https://github.com/oakromulo/flutter_persistent_queue/issues

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  localstorage: ^1.3.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any

